:PROPERTIES:
:ID:       8c46f3d3-2b5b-448b-8c1e-9513bdf8f159
:END:
#+title: Metric Builder Notes
#+last_edited: <2025-12-30 Tue>




* Database Structure
:PROPERTIES:
:ID:       6635314d-03b2-4974-ae05-92bef04d663f
:END:

The Database structure section will go over what our current DB structure looks like. This will go over the data types, as well as the tables. Within each table, there can be sections/columns/etc. that are called into another, which will will try to highlight here.

** events
:PROPERTIES:
:ID:       d4fdfb91-f603-4a81-bfaa-06b498c49505
:END:
Events is where we are storing each event that has occured. An event is what is made in the event page, where users specify the syllabi, location, threat levels, and many other aspects. An event is unique, but it can repeat. This can happen say if an AWF has a refly, or a SQDN wants to practice the same exact event. This also occurs often within virtual and constructive scenarios. It is advised and highly recommended that each event is unique for analysis purposes.

- id : uuid | unique id for the event.
